version: 2

models:

  - name: stg_transactions
    description: transactions table stage
    config:
      database: DBT_FS
      schema: DBT_FS
    
  - name: ft_customer_transactions
    description: transactions by customer
    config:
      database: DBT_FS
      schema: DBT_FS
      materialized: table
      tags: ['python']
