version: 2

sources:
  - name: feature_store_source
    description: "feature store sources"
    database: DBT_FS
    schema: RAW
    tables:
      - name: transactions
        description: "transactions including fraudulent data"